# try:
#     numerator=10
#     denominator=0
#     result=numerator/denominator
#     print(result)
# except:
#     print("Error:denominator cannot be 0")    
# try:
#     print(x)
# except NameError:
#     print("an exception occured")
# except:
#     print("X is not defined")
# try:
#     print("hello")
# except:
#     print("someting wentwrong")  
# else:
#     print("nothing went wrong")      
# try:
#     print(x)
# except:
#     print("something went wrong") 
# finally:
#     print("The 'try except'is finished")   